### ISSUE TITLE
Can't send zen from mobile wallet to bittrex 

### ISSUE THREAD

**Issue by ItsmeeBosslady** [ZencashOfficial/zencash-mobile#39] opened 2017-10-20 02:59 UTC
Android version 4.4.2. 
Entered deposit address, trx speed/fee, but can't click on send button...

**Comment by alexanderzabuga** [comment] 2017-10-22 06:56
that doesn't seem right and I for one have successfully sent my zen to bittrex from mobile wallet two times now. needs more info why it doesn't work for you, probably mistake on your part

**Comment by kendricktan** [comment] 2017-10-22 22:22
What model is the phone?

**Comment by joeblow5656** [comment] 2017-10-25 05:11
Mine will let you click but won't send. Only error.

**Comment by joeblow5656** [comment] 2017-10-25 05:13
Please help I need the money

**Comment by kendricktan** [comment] 2017-10-25 09:39
@joeblow5656

Try clearing the cache of zen wallet and data of zen wallet. **back up your secret phrase and/or keys** . The endpoint which the wallet uses to send transactions had a certificate update.

**Comment by joeblow5656** [comment] 2017-10-25 10:31
Did what you said. Didn't work

**Comment by kendricktan** [comment] 2017-10-25 10:37
I need more information to help you debug. What version of Android are you using?

Where does it fail?
What error message does it throw?

**Comment by joeblow5656** [comment] 2017-10-25 10:46
Android 6.0

**Comment by joeblow5656** [comment] 2017-10-25 10:52
So if I send all I get code 26. If I lower the amount then code 25. No
thing seems to help

**Comment by kendricktan** [comment] 2017-10-25 11:10
Can you screenshot it

**Comment by joeblow5656** [comment] 2017-10-25 11:12
Did you get the photo I sent

**Comment by joeblow5656** [comment] 2017-10-25 11:39
Did you get the photo

**Comment by joeblow5656** [comment] 2017-10-25 12:10
On Oct 25, 2017 4:39 PM, "Kendrick Tan" <notifications@github.com> wrote:

@joeblow5656 <https://github.com/joeblow5656>

Try clearing the cache of zen wallet and data of zen wallet. *back up your
secret phrase and/or keys* . The endpoint which the wallet uses to send
transactions had a certificate update.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ZencashOfficial/zencash-mobile/issues/39#issuecomment-339273976>,
or mute the thread

**Comment by kendricktan** [comment] 2017-10-25 13:33
Nope, still can't see the screenshot :frowning:

**Comment by joeblow5656** [comment] 2017-10-25 13:38
I sent it twice. I attached it to the email.



On Oct 25, 2017 8:33 PM, "Kendrick Tan" <notifications@github.com> wrote:

Nope, still can't see the screenshot 😦

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ZencashOfficial/zencash-mobile/issues/39#issuecomment-339331116>,
or mute the thread

**Comment by kendricktan** [comment] 2017-10-25 14:52
Your attachments aren't going to be visible through GitHub.

GitHub email reply system strips the attachments before posting it onto GitHub.

I don't have your screenshot. Post it through GitHub.

**Comment by kendricktan** [comment] 2017-10-25 22:55
The website recently updated their certificates, you'll need to try and reset your ssl cache. 

Here's a guide: http://www.androidcrush.com/fix-ssl-connection-error-android/

**Comment by joeblow5656** [comment] 2017-10-26 00:56
ok great i did what it said and now my wallet is gone!

1. i reset network setings
2. cleared cach and data
3. uninstalled and reinstalled zen wallet
4. re-entered the pass phrase
6. poof wallet and money are gone
i checked to see if the address is the same for the wallet and it isn't
some how pass phrase is bringing me to new wallet now
what do i do now? i still have the keys but how to use them?

**Comment by joeblow5656** [comment] 2017-10-26 01:03
ok 1 letter was wrong sorry wallet back. my bad i accept. But the bad news
is still the same problem

**Comment by joeblow5656** [comment] 2017-10-26 01:05
it's the same across both of my wifi and my 4g

**Comment by joeblow5656** [comment] 2017-10-26 01:17
Does it matter that I am in Thailand? Maybe time stamp? I offering ideas.
Lol I don't really know much

On Oct 26, 2017 8:05 AM, "Brian" <bmeade17@gmail.com> wrote:

it's the same across both of my wifi and my 4g

**Comment by kendricktan** [comment] 2017-10-26 01:39
What device are you using? And also what version of the app is that? It doesn't matter where you are.

**Comment by joeblow5656** [comment] 2017-10-26 01:42
Huawei media pad t2 7.0

**Comment by joeblow5656** [comment] 2017-10-26 01:43
0.0.6

**Comment by joeblow5656** [comment] 2017-10-26 01:46
The wallet is a fresh download from Google play store

On Oct 26, 2017 8:43 AM, "Brian" <bmeade17@gmail.com> wrote:

0.0.6

**Comment by joeblow5656** [comment] 2017-10-26 03:22
any ideas? how can i get this money while i wait for this to be fixed?

**Comment by alexanderzabuga** [comment] 2017-10-26 03:34
You could try and use myzenwallet.io if you just want to send money
somewhere

**Comment by joeblow5656** [comment] 2017-10-26 03:41
so i don't understand is my coins stuck in this wallet or can i download another wallet and enter the keys and get my money with out using this wallet? or must it be sent to the other wallet by this wallet?

**Comment by alexanderzabuga** [comment] 2017-10-26 03:43
your coins are never stuck in any wallet as long as you have your private
keys. only private keys matter, everything else is built on top of them.
you could input your private key into myzenwallet.io and access your fund
rigth now for example.

**Comment by joeblow5656** [comment] 2017-10-26 03:45
ok so what about elios wallet? i just downloaded that will it allow me to do the same?

**Comment by alexanderzabuga** [comment] 2017-10-26 03:45
Please don't use eleos, get swing or arisen, but basically yes.

**Comment by joeblow5656** [comment] 2017-10-26 03:48
snap it worked your a life saver

**Comment by joeblow5656** [comment] 2017-10-26 03:49
you have no idea the stress i was under. the wife was so mad i invested in these rigs and i lost the money.

**Comment by joeblow5656** [comment] 2017-10-26 03:57
i'm rich. lol i get to live another day

**Comment by alexanderzabuga** [comment] 2017-10-26 04:02
Please get to know how blockchain works and never be stressed again. As
long as you have your private keys only you are in control of your funds

**Comment by max1ne** [comment] 2017-10-26 14:40
I had exactly same issue with error -25 and -26 when sending ZEN to Bittrex. Had tried delete data and cache. Issue still persist :(

**Comment by kendricktan** [comment] 2017-10-26 22:11
Sounds drastic but try factory resetting your phone
 I have no idea how to permanently fix this because of the nature of Android.

**Comment by aayanl** [comment] 2017-10-26 22:13
You need to reset the phone to clear the certificate cache. An alternative is to root the phone and clear it out manually but your zen would be at risk since your phone isnt secure.

**Comment by joeblow5656** [comment] 2017-10-28 04:43
you think the makers of this would have fixed this so we could move on. It
seems maybe the dev side of this wallet is volunteer and not payed? i have
to say i will not screw my whole phone which has many wallets so i can fix
this one if the devs them selves can't seem to find the time to do it. i
will use another wallet.

**Comment by max1ne** [comment] 2017-10-31 15:52
So I noticed v0.0.7 is avail at Google Play. Installed it recently and seems not solved the problem. I tried to reset network settings, but still same result. Is there any way out instead of reset phone to factory default? Any Android expert around?

**Comment by Daruzi** [comment] 2017-11-02 12:47
Use old version v0.0.5. Problem solved

https://github.com/ZencashOfficial/zencash-mobile/releases/tag/v0.0.5

**Comment by max1ne** [comment] 2017-11-02 13:08
Super! It works like charm. Thank a bunch Daruzi ;)

**Comment by max1ne** [comment] 2017-11-03 07:24
And it works also after upgraded to recent v0.0.7 
I guess the v0.0.5 somehow refresh the stuck SSL certificate issue for Bittrex.

**Comment by joeblow5656** [comment] 2017-11-03 07:50
I can confirm that uninstalling 7.0 and reinstalling 5.0 fixed the problem for now. Will update in 2 days to see if it still works.

**Comment by joeblow5656** [comment] 2017-11-03 07:52
Thanks for the idea. The force is strong with this one. Lol

**Comment by joeblow5656** [comment] 2017-11-04 01:33
Maybe a refresh button for ssl is needed for this problem instead of sending the user to reset their phone.

**Comment by max1ne** [comment] 2017-11-04 08:22
Oh No... the issue comes back. It was still OK until yesterday when I used v0.0.7
Any chance Bittrex refresh their SSL certificate again??  I guess I need to come back to v0.0.5 again to fix this issue :(

**Comment by max1ne** [comment] 2017-11-06 15:36
At the moment I stick with v0.0.5 and disable auto-update. In the meanwhile seems Coinomi has been made as the 2nd Android ZEN wallet available in the market after Zencash-mobile. Just saying...

**Comment by kendricktan** [comment] 2017-11-08 13:06
Should be fixed in https://github.com/ZencashOfficial/zencash-mobile/releases/tag/v0.0.8

**Closed by kendricktan** 2017-11-08 13:06 UTC
